### ISSUE TITLE
GitHub Pages for your website

### ISSUE THREAD

**Issue by ana-bautista** [florinpop17/app-ideas#118]
In the Readme file you talk about a future website. Why not create a GitHub Page? Is very easy to configure and the content of the web is what you have in  your readme file. Perfect, no?

**Comment by florinpop17** [comment]
That is an interesting idea @ana-bautista. I'll think about it! Thanks

**Comment by SiddharthVarshney** [comment]
I addition you can also create a form where we can submit ideas rather than creating .md file.
You can also write scripts to crate .md file when the form is submitted.

**Comment by florinpop17** [comment]
@SiddharthVarshney that is something I had in my mind for a while, but I don't yet have the time to do it 🙂

**Comment by jferragut** [comment]
Go Gatsby or go home! lol :) I'm bias though. But yea, Github pages is a great idea and form too!

**Comment by MCacciano** [comment]
I put a PR in that has a very minimal Gatsby frontend built if anyone wants to check it out

**Comment by hikky08** [comment]
I can make the survey  form where we submit our ideas
