### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by W-alley** [florinpop17/app-ideas#126]
Additional context you could add could be a tic-tac-toe game.  It is simple coding that lets the player choose where to put an X then a randomly generated O is produced.  When coding, there would be set "winning game" that knows what a winning (or losing) board looks like and compares it to the actual game board.  It is a pretty easy game to code and fun to play.

**Comment by florinpop17** [comment]
Feel free to create a pull request with tic-tac-toe and I'll add it 😊. Make sure you follow the guidance.
