### ISSUE TITLE
Additional columns on "Projects" table

### ISSUE THREAD

**Issue by eduardoltorres** [florinpop17/app-ideas#17]
When reading the README, I felt like I wanted more information about the [Projects](https://github.com/florinpop17/app-ideas#projects) before diving into each one by clicking them. Perhaps adding a couple of columns with a short sample of the instructions and an example of the project could help potential users browse and choose the idea in a friendlier manner.

For example:

Name | Instructions | Example
--- | --- | --- |
[Christmas Lights](https://github.com/florinpop17/app-ideas/blob/master/Projects/Christmas-Lights-App.md) | Draw seven colored circles in a row and based on a timer change the intensity of each each circle | [PureCSSChristmasLights](https://codepen.io/tobyj/pen/QjvEex)
[Color Cycle](https://github.com/florinpop17/app-ideas/blob/master/Projects/Color-Cycle-App.md) | Draw a box filled with a user specified color and makes small changes over time also based on user input | [CSS Color Changing Background](https://codepen.io/SoumyajitChand/pen/wjKVed)

_Edit:_ couldn't find the way to add the "new idea" label

_Edit 2:_ if you like the idea, I can implement it for the current Projects table and submit a PR :)

**Comment by florinpop17** [comment]
Good idea, I'm just thinking how we'll add all the instructions in that table. 🤔 Some of the project have longer descriptions. What do you say?

**Comment by jdmedlock** [comment]
This is a good idea. I suggest we do the following. Add a short description and a tier number to the app table in README.md. This will provide the viewer with information about the app as well as what level of expertise is required to complete it. We'll include a definition of the tiers in the README.md as well.

**Comment by eduardoltorres** [comment]
Hmm, yes...it would have to be a single sentence that would summarize the project, just like in my example.

If it is **too** complicated for some projects, perhaps that instructions could be something even more general. For example, if it is a super complex Pomodoro timer with lots of functionalities, the instructions could be something like: "Pomodoro timer with distinct dynamic functionalities". That way the person knows it is a timer but a complicated one. What do you think?

_Update:_ as I was writing this, I saw @jdmedlock 's suggestion which sounds great. Let me know if I can help in any way.

**Comment by jdmedlock** [comment]
Here's a more concrete example. Each detailed app specification start with the summary info:

![image](https://user-images.githubusercontent.com/1287072/54496240-0f0b6500-48bb-11e9-9a4d-b7a53677535f.png)

We'll incorporate this info into the README.md so it looks like this:

![image](https://user-images.githubusercontent.com/1287072/54496296-a5d82180-48bb-11e9-8e9b-60944ce20f52.png)

**Comment by florinpop17** [comment]
That's perfect @jdmedlock !! Thank you!
