### ISSUE TITLE
Calorie Counter: Raw Data file does not exist

### ISSUE THREAD

**Issue by minas1** [florinpop17/app-ideas#175]
The _MyPyramid Food Raw Data_ file doesn't seem to exist anymore.

**To Reproduce**
1. Go to [Useful links and resources](https://catalog.data.gov/dataset/mypyramid-food-raw-data-f9ed6)
1. Open the link

The follow error appears: **404 Not Found The resource could not be found. Dataset not found**

![Screenshot_2020-05-04 Error 404 - Data gov](https://user-images.githubusercontent.com/1492092/81005796-2b6bb780-8e57-11ea-9afe-0f5352878794.png)

**Comment by NoellyB76** [comment]
I was able to download the zip file just fine as of 8:44 p.m. Eastern Standard Time.

**Comment by minas1** [comment]
From this link? https://catalog.data.gov/dataset/mypyramid-food-raw-data-f9ed6

That's strange. I am based in Europe by the way - I don't know if it has something to do with it.

**Comment by multitudes** [comment]
I found just by going to the main page and searching:
https://catalog.data.gov/dataset/mypyramid-food-raw-data

https://inventory.data.gov/dataset/794cd3d7-4d28-4408-8f7d-84b820dbf7f2/resource/6b78ec0c-4980-4ad8-9cbd-2d6eb9eda8e7/download/myfoodapediadata.zip

**Comment by minas1** [comment]
> I found just by going to the main page and searching:
> https://catalog.data.gov/dataset/mypyramid-food-raw-data
>

Great! My opinion is that the link should be changed to this one.

**Comment by KontrolG** [comment]
In this link [https://fdc.nal.usda.gov/](url) you can also find the data of the US Department of Agriculture, it is available in CSV and has more information and plenty more foods.
