### ISSUE TITLE
Color Cycle App - CSS Color Code Link Broken

### ISSUE THREAD

**Issue by singhmi4** [florinpop17/app-ideas#180]
**Describe the bug**
In the Beginner Level Project: Color Cycle App, section Useful Links and References, the link: (https://www.quackit.com/css/css_color_codes.cfm) is broken.

**To Reproduce**
1. Go to Color Cycle App
2. Scroll down to Useful links and resources
3. Click on (https://www.quackit.com/css/css_color_codes.cfm)
4. See Error

**Expected behavior**
The link should direct to a page about color codes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version [76]

**Comment by Pega-sys** [comment]
Well the quackit.com domain was hijacked. 
You can find the CSS color codes information here.
link: - [https://www.qhmit.com/css/css_color_codes.cfm]
