### ISSUE TITLE
The User Stories in Beginner Project Dynamic CSS Variables doesn't seem to match the Example Project

### ISSUE THREAD

**Issue by singhmi4** [florinpop17/app-ideas#187]
**Describe the bug**

- https://github.com/florinpop17/app-ideas/blob/master/Projects/1-Beginner/Dynamic-CSSVar-app.md

- The User Stories in Beginner Project Dynamic CSS Variables doesn't seem to match the Example Project.

- The user stories to describe a user login experience whereas the example project shows in-app controls to manipulate a box.

**Expected behavior**

- Believe the User Stories are incorrect for the purpose of dynamic CSS variable manipulation for this project.

**Comment by florinpop17** [comment]
The example projects might not be 100% accurate. Feel free to create one that is 😊
