### ISSUE TITLE
adding of project in tier 1

### ISSUE THREAD

**Issue by Anmolreshi** [florinpop17/app-ideas#193]
Adding management system app like **hotel management**  would provide a great project ! i could contribute towards the code as i have made it ! let me known if you are interested in this plan . it would require guest reservation , checkout,dining , available rooms ,pricing from top rooms to medium level ones .

**Comment by Augustine-source** [comment]
Interested

**Comment by alexmercerr07** [comment]
Interested

**Comment by Anmolreshi** [comment]
Hi,
You want to contribute towards the different ideas for this project?

**Comment by Augustine-source** [comment]
Oh yes

**Comment by Anmolreshi** [comment]
If you have modification on this project idea you could follow me and revert back there ! open to ideas
