### ISSUE TITLE
4Th Category

### ISSUE THREAD

**Issue by rob84044** [florinpop17/app-ideas#34]
I do not know if this is something you guys are already doing, can I request a 4th category of projects that will help walk people through creating specific projects?

Like How to create a website that does the following
- blah blah
- blah blah
- - blah blah
- - blah blah
- - blah blah
- - blah blah
- - blah blah

And then step people through creating the HTML, CSS,LESS MVP of the site

Then the vanilla JS MVP

Then JS framework for front end end

Then the back end set up as well?

I know it is no simple thing, I would even be game to pay for access to that repo as that would be PHENOMENAL

**Comment by florinpop17** [comment]
@rob84044 - interesting idea. So the 4th Category would be something like: Fully fledged Web App? 🤔

Could you create an example and we can see how it fits, what do you say? ☺️

**Comment by rob84044** [comment]
It would be a rough outline of an idea as I’m fairly new to programming, but yea, I’d love to!

**Comment by florinpop17** [comment]
It’s ok, we’ll see if the idea fits the current state of the project and if it does, we’ll add it ☺️

**Comment by florinpop17** [comment]
I'll close this issue as of now, we'll wait to see your idea in action in a PR! 😄
