### ISSUE TITLE
Guidance on starting a new project(my first)

### ISSUE THREAD

**Issue by vrindavan** [florinpop17/app-ideas#395]
So, currently I am just familiar with basic languages Java, Python and C++ but rather than just keeping on reading more and more basic problems and practice, I decided to work on my skills through projects and came across your repo. Very helpful, have to say. What my query is, I do not know how to go ahead now as I do not know any front end tech. I would like to work on it but if anyone could guide a bit on how to proceed would be very nice of you. I want to do these projects but my main aim is back end rather than full stack. Might sound like a neophyte but well, that is my query. Can you recommend what & how tech stack(language + framework) should I start leaning now to do these projects like JS, React, Angular, etc.

Thanks!

**Comment by rishikesh2003** [comment]
If you like backend stuff other than frontend you can make nice projects with backend, like creating a nice **api** service and you can **monetize**.
If you want to go into **frontend** then I would suggest  you learning **Javascript** or **Typescript**, I would suggest learning Typescript and you could learn any frontend framework from the following **React** or **Vue**, Then you can go on creating projects. You will start learning more when you start creating projects.
Just find what fits you the most backend, frontend or fullstack.

**Comment by vrindavan** [comment]
Thanks @rishikesh2003 I have decided to go with Full Stack now viz. HTML, CSS, JS, Python, APIs, Django and stuff around that.
