### ISSUE TITLE
Just a place to post our code :)

### ISSUE THREAD

**Issue by lolottetheclash** [florinpop17/app-ideas#40]
Hi!

i just started the first test and i was wondering if it was possible to have a place where we all could share our code in order to be sure it's fine and to improve ourselves!
so , my github link where your can find my first code bin2dec :)
https://github.com/lolottetheclash/Dev_tests/blob/master/Beginner%20Projects/bin2dec.rb
it's in ruby, hope it's all right ;)
thanks a lot for sharing these tests!
lauren

**Comment by florinpop17** [comment]
Well done @lolottetheclash ! Unfortunately I'm not a Ruby developer and I can't really give you a feedback, but maybe @jdmedlock knows Ruby! 😄

**Comment by lolottetheclash** [comment]
hey Florin!

thanks a lot for your answer, it’s sooooo nice to take the time to answer like you do :)
best regards and have a nice evening :)
rain for us in south of france :’(
lauren

**Comment by jdmedlock** [comment]
I'm afraid I don't know Ruby. However, if you'd like to post screenshots of the app I'd be happy to look at them and provide feedback.

**Comment by lolottetheclash** [comment]
thanks a lot @jdmedlock! it's very kind of you! But don't bother i'll try to find a ruby forum to share it it will be easier :) thanks again for your proposition & have a nice day!

**Comment by florinpop17** [comment]
I'll close this ticket now... You can open another one when you'll have some questions!
