### ISSUE TITLE
Add Dice Simulator to Begineer List

### ISSUE THREAD

**Issue by asphalke07** [florinpop17/app-ideas#554]
Application Name: Dice Simulator
Tier: 1-Begineer

Snake and Ladders, Ludo and Checkers, are the most favorite games of all time. But, it feels terrible when we drop the plan of playing just because you couldn’t find the dice. So, here is a fascinating option to give you a chance to make something cool. 
I have an idea to build a Dice Rolling Simulator.
@florinpop17

**Comment by ys1113457623** [comment]
https://github.com/florinpop17/app-ideas/pull/563

DONE
