### ISSUE TITLE
New project idea: Time Tracking

### ISSUE THREAD

**Issue by Sironheart** [florinpop17/app-ideas#587]
**Is your feature request related to a problem? Please describe.**
In the EU there is a law, that enforces employer to track the time spans an employee is working. As this is a 'new' requirement for most companies it makes sense for most people to get used to tracking their working hours now and get used to this behavior.

**Describe the solution you'd like**
An application (web/ native/ backend, does not matter) to track times you start/stop to work and when you take breaks. This can be reached by tracking locations, using a UI, NFC Tags and many other ways. I would recommend implementing a web UI or a native app, since these would be the easiest solution.

**Describe alternatives you've considered**
As described earlier, there could be many options, like tracking your location or using nfc tags and giving calls to an API. There is no real limit to the possibilities you can indicate whether you are working (geolocation for work in an office, nfc for 'enter/leave building', bluetooth connection for 'is at desk', etc)

**Additional context**
As mentioned earlier, in the EU the time tracking of employees is required by law. Some countries already implemented this in their own laws, some still need to implement these laws.
This project is mostly to get used to working with time/dates, maybe even timezones. Also this could be a nice tool to check your own working hours ;)

**Comment by SATWIKOJHA** [comment]
Hello sir can you assign this issue to me

**Comment by SATWIKOJHA** [comment]
[](u
[postman-code-generators-develop.zip](https://github.com/florinpop17/app-ideas/files/9890921/postman-code-generators-develop.zip)



Sending you files please check

**Comment by aldairandre** [comment]
# Hello everyone 👋

I hope this message finds you well. As you may know, the original repository for app ideas has not been updated in a while and is no longer actively maintained. However, I'm excited to let you know that a new repository has been created to continue this project (https://github.com/vincent0426/app-ideas).

The new repository aims to provide a comprehensive list of practical and achievable app ideas that developers of all levels can work on to improve their skills and build their portfolios. We welcome contributions from anyone who wants to add their own app ideas or improve the existing ones, and we are also looking for volunteers who can help maintain the repository and keep it up to date.

If you are interested in contributing or maintaining this project, please head over to the new repository (https://github.com/vincent0426/app-ideas) ⭐ and take a look at the existing issues and pull requests. Feel free to open a new issue if you have an app idea to suggest or if you have any questions about the project.

Thank you for your attention, and I hope to see you in the new repository soon! 💖

<br/>

⚠️ This message was generated by a robot 🤖, if this message reached you, consider leaving a star for this robot, repository link

⭐ https://github.com/aldairandre/github-bot ⭐

**Comment by aldairandre** [comment]
# Hello everyone 👋

I hope this message finds you well. As you may know, the original repository for app ideas has not been updated in a while and is no longer actively maintained. However, I'm excited to let you know that a new repository has been created to continue this project (https://github.com/vincent0426/app-ideas).

The new repository aims to provide a comprehensive list of practical and achievable app ideas that developers of all levels can work on to improve their skills and build their portfolios. We welcome contributions from anyone who wants to add their own app ideas or improve the existing ones, and we are also looking for volunteers who can help maintain the repository and keep it up to date.

If you are interested in contributing or maintaining this project, please head over to the new repository (https://github.com/vincent0426/app-ideas) ⭐ and take a look at the existing issues and pull requests. Feel free to open a new issue if you have an app idea to suggest or if you have any questions about the project.

Thank you for your attention, and I hope to see you in the new repository soon! 💖

<br/>

⚠️ This message was generated by a robot 🤖, if this message reached you, consider leaving a star for this robot, repository link

⭐ https://github.com/aldairandre/github-bot ⭐

**Comment by Prathmesharage** [comment]
Thank you for the update! It's great to hear about the new repository for app ideas. I'll definitely check it out and consider contributing. Keeping such resources up-to-date is crucial for the developer community. Your efforts to maintain and improve the collection are appreciated. Looking forward to exploring the existing ideas and possibly suggesting some of my own. Cheers! 🚀
