### ISSUE TITLE
EUPHORIA CHECK - A Modern PERMA web app based on PERMA Model of Happiness

### ISSUE THREAD

**Issue by Aryainguz** [florinpop17/app-ideas#690]
Would like to add on intermediate level projects a unique web app project - Euphoria-Check

*Euphoria-Check is a web application built in nodejs and expressjs that is based on PERMA Model of Happiness
PERMA - (Positiveness Engagement Relationships Meaning Accomplishment)

*Key Features:

*User answers 20 questions prepared using PERMA model based on different indexes of Happiness
* User recieves final PERMA scores and Email providing insights and improvement based upon deficit on particular PERMA score

link for application  : https://euphoria-check-perma-meter-express-65aqxla74-aryainguz.vercel.app/

**Comment by Casper-69** [comment]
Hey! when i clicked on your application link the browser says there's attackers on this site, pls look into it

**Comment by Aryainguz** [comment]
> Hey! when i clicked on your application link the browser says there's attackers on this site, pls look into it

Yes @Casper-69 that’s a mistake in phishing site maintenance by Google and we’ve reported it successfully would be normal soon.
Thanks for letting me now!
