### ISSUE TITLE
2408 Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [florinpop17/app-ideas#756]
2408 Game
Tier: 2-Intermediate

2048 is a single-player sliding tile puzzle game. The objective of the game is to slide numbered tiles on a grid to combine them to create a tile with the number 2048; however, one can continue to play the game after reaching the goal, creating tiles with larger numbers.
2048 is played on a plain 4×4 grid, with numbered tiles that slide when a player moves them using the four arrow keys. The game begins with two tiles already in the grid, having a value of either 2 or 4, and another such tile appears in a random empty space after each turn. Tiles slide as far as possible in the chosen direction until they are stopped by either another tile or the edge of the grid. If two tiles of the same number collide while moving, they will merge into a tile with the total value of the two tiles that collided. The resulting tile cannot merge with another tile again in the same move. Higher-scoring tiles emit a soft glow;[5] the largest possible tile is 131,072.

![main-qimg-8539fa092233868419d8d378c230f605-pjlq](https://github.com/florinpop17/app-ideas/assets/146121869/70db143b-d1e2-4b93-ad8e-a35767b43e0c)

**Comment by AsmitaMishra24** [comment]
Please assign me this issue under hactoberfest 2023 tag

**Comment by Vikas3100** [comment]
Hello 
I want to begin my first contribution  with this project can you please assign it to me.
