### ISSUE TITLE
Show Available Programming Languages 

### ISSUE THREAD

**Issue by serinachen00** [florinpop17/app-ideas#81]
I am a Java language "tier 1" student. I saw your open source and very interested in it. My primary programming Language is Java. Would you like to put Java Language in your projects as well? When I read your "READ ME", I didn't see what kind of programming languages is open for developers to use. It will be great if you mention a couple of few Front End and Back End programming languages. For Example: Java, Python, React, HTML, CSS, Ruby etc.

**Comment by pburkart** [comment]
As far as I know, there are no limitations on what programming languages can be used, unless otherwise specified in the app description.

**Comment by florinpop17** [comment]
Good idea @pburkart !

**Comment by florinpop17** [comment]
@serinachen00 the projects are created with no programming language in mind, although some of the projects are more or less "web" related, so you can use any programming language you want.
